name: CI Pipeline
on:
  push:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # ---------- PHP / Symfony ----------
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3

      - name: Create Symfony .env
        working-directory: symfony-api
        run: cp .env.dev .env

      - name: Install Symfony deps
        working-directory: symfony-api
        run: composer install --no-interaction --prefer-dist

      - name: Create var directory
        working-directory: symfony-api
        run: mkdir -p var

      - name: Create test database schema
        working-directory: symfony-api
        run: php bin/console doctrine:schema:create --env=test

      - name: Run Symfony tests
        working-directory: symfony-api
        run: php bin/phpunit

      # ---------- Node / Express ----------
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Express deps
        working-directory: express-app
        run: npm install

      - name: Run Express tests
        working-directory: express-app
        run: npm test

  docker:
    runs-on: ubuntu-latest
    needs: test
    permissions:
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build & Push Symfony image
        uses: docker/build-push-action@v5
        with:
          context: ./symfony-api
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/cat-symfony:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/cat-symfony:${{ github.sha }}

      - name: Build & Push Express image
        uses: docker/build-push-action@v5
        with:
          context: ./express-app
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/cat-express:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/cat-express:${{ github.sha }}